const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Arr,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.solid,
		C3.Plugins.LocalStorage,
		C3.Plugins.Clipboard,
		C3.Behaviors.scrollto,
		C3.Plugins.EMI_INDO_LogMessage,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Dictionary,
		C3.Plugins.Particles,
		C3.Plugins.Multiplayer,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Browser.Acts.SetWindowSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.EMI_INDO_LogMessage.Acts.logMessage,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLoad,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.GamePush_Channels.Acts.SendFeedMessage,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.GamePush_Channels.Acts.FetchFeedMessages,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.GamePush_Channels.Cnds.OnFeedMessagesFetch,
		C3.Plugins.GamePush_Channels.Cnds.EachMessage,
		C3.Plugins.GamePush_Channels.Acts.DeleteMessage,
		C3.Plugins.GamePush_Channels.Exps.CurMessageID,
		C3.JavaScriptInEvents.Main_Event14_Act3,
		C3.JavaScriptInEvents.Main_Event15_Act1,
		C3.JavaScriptInEvents.Main_Event16_Act1,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsIsPurchased,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchScoped,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerPosition,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerIndex,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerField,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Multiplayer.Cnds.IsSupported,
		C3.Plugins.Multiplayer.Acts.AddClientInputValue,
		C3.Plugins.Multiplayer.Acts.SyncObject,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Exps.PeerLatency,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Cnds.OnClientUpdate,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Multiplayer.Exps.HostAlias,
		C3.Plugins.Multiplayer.Exps.PeerAliasFromID,
		C3.JavaScriptInEvents.Referral_Event2_Act1,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Multiplayer.Exps.PeerCount,
		C3.Plugins.Multiplayer.Exps.StatInboundCount,
		C3.Plugins.Multiplayer.Exps.StatInboundBandwidth,
		C3.Plugins.Multiplayer.Exps.StatOutboundCount,
		C3.Plugins.Multiplayer.Exps.StatOutboundBandwidth,
		C3.Plugins.Multiplayer.Exps.PeerPDV,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Acts.SignallingLeaveRoom,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.Multiplayer.Acts.InputPredictObject,
		C3.Plugins.Multiplayer.Acts.SetClientState,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.setbit,
		C3.Plugins.System.Exps.getbit,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Multiplayer.Exps.PeerState,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Multiplayer.Exps.LagCompensateX,
		C3.Plugins.Multiplayer.Exps.LagCompensateY,
		C3.Plugins.Multiplayer.Exps.LagCompensateAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{AimSpot: 0},
	{HostIndicator: 0},
	{NetStats: 0},
	{peerid: 0},
	{lookatx: 0},
	{lookaty: 0},
	{inputs: 0},
	{health: 0},
	{kills: 0},
	{deaths: 0},
	{FirstShot: 0},
	{lasthitbypeerid: 0},
	{winner: 0},
	{started: 0},
	{ended: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Platform: 0},
	{Peer: 0},
	{PeerLaser: 0},
	{PeerName: 0},
	{LogText: 0},
	{LogMessages: 0},
	{Sine: 0},
	{mining: 0},
	{Rotate: 0},
	{pick: 0},
	{ground: 0},
	{Anchor: 0},
	{usdt_: 0},
	{Browser: 0},
	{b1: 0},
	{usdtbg: 0},
	{PlatformInfo: 0},
	{mineinfo: 0},
	{Touch: 0},
	{GamePush: 0},
	{Usdt: 0},
	{Solid: 0},
	{digging_platform: 0},
	{settingsuiSquareBlack: 0},
	{settings_icon: 0},
	{mining_icon: 0},
	{comingsoon: 0},
	{pvp_icon: 0},
	{uiinfo: 0},
	{main_icon: 0},
	{Sprite: 0},
	{pick2: 0},
	{shop_: 0},
	{coin_icon: 0},
	{coin: 0},
	{chest_icon: 0},
	{rw_x2button: 0},
	{LocalStorage: 0},
	{rw_info: 0},
	{adv_icon: 0},
	{digmetre: 0},
	{flapster: 0},
	{Leaders_text: 0},
	{Leaders: 0},
	{wallet_: 0},
	{autoflash_: 0},
	{ironpickaxe_shopitem: 0},
	{goldpickaxe_shopitem: 0},
	{crimsonpickaxe_shopitem: 0},
	{emeraldpickaxe_shopitem: 0},
	{energy_bg: 0},
	{tag: 0},
	{InitialWidth: 0},
	{energy_bar: 0},
	{energy_text: 0},
	{user_id: 0},
	{settingsui: 0},
	{walletsui: 0},
	{settingstext: 0},
	{settingsuiexit: 0},
	{Clipboard: 0},
	{copybutton: 0},
	{shopbutton1: 0},
	{shopbutton2: 0},
	{shopbutton3: 0},
	{shopbutton4: 0},
	{shopbuttontext1: 0},
	{shopbuttontext2: 0},
	{shopbuttontext3: 0},
	{shopbuttontext4: 0},
	{loading_bg: 0},
	{coin_item1: 0},
	{coin_item2: 0},
	{coin_item3: 0},
	{Sine2: 0},
	{loading_bar: 0},
	{walletui: 0},
	{settingui2: 0},
	{walletuiexit: 0},
	{walletuiSquareBlack: 0},
	{walletuitext: 0},
	{connectusbutton: 0},
	{connectustext: 0},
	{walletmintext: 0},
	{b2: 0},
	{mineinfo2: 0},
	{mineinfo3: 0},
	{PrevY: 0},
	{CurY: 0},
	{DiffY: 0},
	{ScrollTo: 0},
	{scroll: 0},
	{LogMessage: 0},
	{diamondpickaxe_shopitem: 0},
	{uishopbg: 0},
	{nav_market: 0},
	{navshop_info: 0},
	{nav_market2: 0},
	{nav_market3: 0},
	{tg_star: 0},
	{shopbutton5: 0},
	{shopbuttontext5: 0},
	{uicoin: 0},
	{uicoin2: 0},
	{add_: 0},
	{trophy_: 0},
	{file_: 0},
	{taskexit: 0},
	{player_avatar: 0},
	{Username: 0},
	{uicoin3: 0},
	{Leaderstext: 0},
	{userleaderboard: 0},
	{autolobbytext: 0},
	{Array: 0},
	{GamePushChannels: 0},
	{Enemy: 0},
	{uiinfo_task: 0},
	{uiinfo_market: 0},
	{uiinfo_home: 0},
	{uiinfo_pvp: 0},
	{uiinfo_mining: 0},
	{prtcofplatform: 0},
	{bgleaders: 0},
	{leaderboardbg: 0},
	{leadersbg2: 0},
	{leadersbg3: 0},
	{leaderboardbg2: 0},
	{leaderboardbg3: 0},
	{leaderboardbg4: 0},
	{top1icon: 0},
	{top2icon: 0},
	{top3icon: 0},
	{leaderboardinfo: 0},
	{leaderboardshineeffect: 0},
	{bgmine: 0},
	{bgleaders2: 0},
	{taskbar_1: 0},
	{task1_text: 0},
	{taskbar_1button: 0},
	{bgleaders3: 0},
	{bgleaders4: 0},
	{task1_text1: 0},
	{task1_coin: 0},
	{task2_coin: 0},
	{taskbar_2button: 0},
	{task2_text2: 0},
	{task2_text: 0},
	{users_: 0},
	{uiinfo_referral: 0},
	{Referral_text: 0},
	{textbox_reflink: 0},
	{textbox_invite: 0},
	{textbox3: 0},
	{Referrallink_text: 0},
	{referralcount_text: 0},
	{referralinfoincometext: 0},
	{earnedfromreferrals: 0},
	{taskbar_3button: 0},
	{task3_coin: 0},
	{task3_text3: 0},
	{Leaderstext2: 0},
	{DigOrDie: 0},
	{Multiplayer: 0},
	{PvP: 0},
	{Ground_: 0},
	{Ground_2: 0},
	{Ground_3: 0},
	{Ground_4: 0},
	{Ground_5: 0},
	{Ground_6: 0},
	{Ground_7: 0},
	{Ground_8: 0},
	{Ground_9: 0},
	{Ground_10: 0},
	{Ground_11: 0},
	{Ground_12: 0},
	{Ground_13: 0},
	{Health: 0},
	{P1: 0},
	{stats: 0},
	{ScoreDisplay: 0},
	{Title: 0},
	{NameTextBox: 0},
	{JoinButton: 0},
	{FormLabel: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{P2: 0},
	{go_left: 0},
	{go_right: 0},
	{finish: 0},
	{P3: 0},
	{finish2: 0},
	{exit_: 0},
	{yourleaderplace: 0},
	{ru: 0},
	{settingsinfo: 0},
	{P4: 0},
	{wifi: 0},
	{mine: 0},
	{mine2: 0},
	{mine3: 0},
	{digordiebutton: 0},
	{digordiebutton2: 0},
	{coin2: 0},
	{Usdt2: 0},
	{coinpvp: 0},
	{taskbar_4button: 0},
	{task4_coin: 0},
	{task4_text4: 0},
	{AimSpotFamily: 0},
	{AimSpotFamily2: 0},
	{mine_section: 0},
	{dsafweqwdgetgefwqeqewqdwcvfrffd: 0},
	{click: 0},
	{x2_timer: 0},
	{coin_backendtime: 0},
	{coin_backend: 0},
	{Referral_level1: 0},
	{Referral_level2: 0},
	{Referral_level3: 0},
	{check_if_registered: 0},
	{jndkfhduriehrfbkhge: 0},
	{item1_bought: 0},
	{item2_bought: 0},
	{item3_bought: 0},
	{item4_bought: 0},
	{item5_bought: 0},
	{Selected: 0},
	{task1_status: 0},
	{task2_status: 0},
	{task3_status: 0},
	{MyUsername: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{GameState: 0},
	{state: 0},
	{player_id: 0},
	{ref_link: 0},
	{parent_candidate: 0},
	{plyid: 0},
	{referral_earnusdt: 0},
	{Peer_id: 0},
	{Host_id: 0},
	{message: 0},
	{alias: 0},
	{OldX: 0},
	{OldY: 0},
	{OldAngle: 0},
	{aimSpotUid: 0},
	{firingPeerId: 0}
];

self.InstanceType = {
	AimSpot: class extends self.ISpriteInstance {},
	HostIndicator: class extends self.ITextInstance {},
	NetStats: class extends self.ITextInstance {},
	Peer: class extends self.ISpriteInstance {},
	PeerLaser: class extends self.ISpriteInstance {},
	PeerName: class extends self.ITextInstance {},
	LogText: class extends self.ITextInstance {},
	LogMessages: class extends self.IArrayInstance {},
	mining: class extends self.ISpriteInstance {},
	pick: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	usdt_: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	b1: class extends self.ISpriteInstance {},
	usdtbg: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	mineinfo: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Usdt: class extends self.ITextInstance {},
	digging_platform: class extends self.ISpriteInstance {},
	settingsuiSquareBlack: class extends self.ISpriteInstance {},
	settings_icon: class extends self.ISpriteInstance {},
	mining_icon: class extends self.ISpriteInstance {},
	comingsoon: class extends self.ITextInstance {},
	pvp_icon: class extends self.ISpriteInstance {},
	uiinfo: class extends self.ITextInstance {},
	main_icon: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pick2: class extends self.ISpriteInstance {},
	shop_: class extends self.ISpriteInstance {},
	coin_icon: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {},
	chest_icon: class extends self.ISpriteInstance {},
	rw_x2button: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	rw_info: class extends self.ITextInstance {},
	adv_icon: class extends self.ISpriteInstance {},
	flapster: class extends self.ISpriteInstance {},
	Leaders_text: class extends self.ITextInstance {},
	Leaders: class extends self.IArrayInstance {},
	wallet_: class extends self.ISpriteInstance {},
	autoflash_: class extends self.ISpriteInstance {},
	ironpickaxe_shopitem: class extends self.ISpriteInstance {},
	goldpickaxe_shopitem: class extends self.ISpriteInstance {},
	crimsonpickaxe_shopitem: class extends self.ISpriteInstance {},
	emeraldpickaxe_shopitem: class extends self.ISpriteInstance {},
	energy_bg: class extends self.ISpriteInstance {},
	energy_bar: class extends self.ISpriteInstance {},
	energy_text: class extends self.ITextInstance {},
	user_id: class extends self.ITextInstance {},
	settingsui: class extends self.ISpriteInstance {},
	walletsui: class extends self.ISpriteInstance {},
	settingstext: class extends self.ITextInstance {},
	settingsuiexit: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	copybutton: class extends self.ISpriteInstance {},
	shopbutton1: class extends self.ISpriteInstance {},
	shopbutton2: class extends self.ISpriteInstance {},
	shopbutton3: class extends self.ISpriteInstance {},
	shopbutton4: class extends self.ISpriteInstance {},
	shopbuttontext1: class extends self.ITextInstance {},
	shopbuttontext2: class extends self.ITextInstance {},
	shopbuttontext3: class extends self.ITextInstance {},
	shopbuttontext4: class extends self.ITextInstance {},
	loading_bg: class extends self.ISpriteInstance {},
	coin_item1: class extends self.ISpriteInstance {},
	coin_item2: class extends self.ISpriteInstance {},
	coin_item3: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ISpriteInstance {},
	walletui: class extends self.ISpriteInstance {},
	settingui2: class extends self.ISpriteInstance {},
	walletuiexit: class extends self.ISpriteInstance {},
	walletuiSquareBlack: class extends self.ISpriteInstance {},
	walletuitext: class extends self.ITextInstance {},
	connectusbutton: class extends self.ISpriteInstance {},
	connectustext: class extends self.ITextInstance {},
	walletmintext: class extends self.ITextInstance {},
	b2: class extends self.ISpriteInstance {},
	mineinfo2: class extends self.ITextInstance {},
	mineinfo3: class extends self.ITextInstance {},
	scroll: class extends self.ISpriteInstance {},
	LogMessage: class extends C3.Plugins.EMI_INDO_LogMessage.Instance {},
	diamondpickaxe_shopitem: class extends self.ISpriteInstance {},
	uishopbg: class extends self.ISpriteInstance {},
	nav_market: class extends self.ISpriteInstance {},
	navshop_info: class extends self.ITextInstance {},
	nav_market2: class extends self.ISpriteInstance {},
	nav_market3: class extends self.ISpriteInstance {},
	tg_star: class extends self.ISpriteInstance {},
	shopbutton5: class extends self.ISpriteInstance {},
	shopbuttontext5: class extends self.ITextInstance {},
	uicoin: class extends self.ISpriteInstance {},
	uicoin2: class extends self.ISpriteInstance {},
	add_: class extends self.ISpriteInstance {},
	trophy_: class extends self.ISpriteInstance {},
	file_: class extends self.ISpriteInstance {},
	taskexit: class extends self.ISpriteInstance {},
	player_avatar: class extends self.ISpriteInstance {},
	Username: class extends self.ITextInstance {},
	uicoin3: class extends self.ISpriteInstance {},
	Leaderstext: class extends self.ITextInstance {},
	userleaderboard: class extends self.ISpriteInstance {},
	autolobbytext: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	GamePushChannels: class extends C3.Plugins.GamePush_Channels.Instance {},
	Enemy: class extends self.IDictionaryInstance {},
	uiinfo_task: class extends self.ITextInstance {},
	uiinfo_market: class extends self.ITextInstance {},
	uiinfo_home: class extends self.ITextInstance {},
	uiinfo_pvp: class extends self.ITextInstance {},
	uiinfo_mining: class extends self.ITextInstance {},
	prtcofplatform: class extends self.IParticlesInstance {},
	bgleaders: class extends self.ISpriteInstance {},
	leaderboardbg: class extends self.ISpriteInstance {},
	leadersbg2: class extends self.ISpriteInstance {},
	leadersbg3: class extends self.ISpriteInstance {},
	leaderboardbg2: class extends self.ISpriteInstance {},
	leaderboardbg3: class extends self.ISpriteInstance {},
	leaderboardbg4: class extends self.ISpriteInstance {},
	top1icon: class extends self.ISpriteInstance {},
	top2icon: class extends self.ISpriteInstance {},
	top3icon: class extends self.ISpriteInstance {},
	leaderboardinfo: class extends self.ISpriteInstance {},
	leaderboardshineeffect: class extends self.ISpriteInstance {},
	bgmine: class extends self.ISpriteInstance {},
	bgleaders2: class extends self.ISpriteInstance {},
	taskbar_1: class extends self.ISpriteInstance {},
	task1_text: class extends self.ITextInstance {},
	taskbar_1button: class extends self.ISpriteInstance {},
	bgleaders3: class extends self.ISpriteInstance {},
	bgleaders4: class extends self.ISpriteInstance {},
	task1_text1: class extends self.ITextInstance {},
	task1_coin: class extends self.ISpriteInstance {},
	task2_coin: class extends self.ISpriteInstance {},
	taskbar_2button: class extends self.ISpriteInstance {},
	task2_text2: class extends self.ITextInstance {},
	task2_text: class extends self.ITextInstance {},
	users_: class extends self.ISpriteInstance {},
	uiinfo_referral: class extends self.ITextInstance {},
	Referral_text: class extends self.ITextInstance {},
	textbox_reflink: class extends self.ISpriteInstance {},
	textbox_invite: class extends self.ISpriteInstance {},
	textbox3: class extends self.ISpriteInstance {},
	Referrallink_text: class extends self.ITextInstance {},
	referralcount_text: class extends self.ITextInstance {},
	referralinfoincometext: class extends self.ITextInstance {},
	earnedfromreferrals: class extends self.ITextInstance {},
	taskbar_3button: class extends self.ISpriteInstance {},
	task3_coin: class extends self.ISpriteInstance {},
	task3_text3: class extends self.ITextInstance {},
	Leaderstext2: class extends self.ITextInstance {},
	DigOrDie: class extends self.ISpriteInstance {},
	Multiplayer: class extends self.IInstance {},
	PvP: class extends self.ISpriteInstance {},
	Ground_: class extends self.ISpriteInstance {},
	Ground_2: class extends self.ISpriteInstance {},
	Ground_3: class extends self.ISpriteInstance {},
	Ground_4: class extends self.ISpriteInstance {},
	Ground_5: class extends self.ISpriteInstance {},
	Ground_6: class extends self.ISpriteInstance {},
	Ground_7: class extends self.ISpriteInstance {},
	Ground_8: class extends self.ISpriteInstance {},
	Ground_9: class extends self.ISpriteInstance {},
	Ground_10: class extends self.ISpriteInstance {},
	Ground_11: class extends self.ISpriteInstance {},
	Ground_12: class extends self.ISpriteInstance {},
	Ground_13: class extends self.ISpriteInstance {},
	P1: class extends self.ISpriteInstance {},
	stats: class extends self.ITextInstance {},
	ScoreDisplay: class extends self.ITextInstance {},
	Title: class extends self.ITextInstance {},
	NameTextBox: class extends self.ITextInputInstance {},
	JoinButton: class extends self.IButtonInstance {},
	FormLabel: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	P2: class extends self.ISpriteInstance {},
	go_left: class extends self.ISpriteInstance {},
	go_right: class extends self.ISpriteInstance {},
	finish: class extends self.ISpriteInstance {},
	P3: class extends self.ISpriteInstance {},
	finish2: class extends self.ISpriteInstance {},
	exit_: class extends self.ISpriteInstance {},
	yourleaderplace: class extends self.ITextInstance {},
	ru: class extends self.ISpriteInstance {},
	settingsinfo: class extends self.ITextInstance {},
	P4: class extends self.ISpriteInstance {},
	wifi: class extends self.ISpriteInstance {},
	mine: class extends self.ISpriteInstance {},
	mine2: class extends self.ISpriteInstance {},
	mine3: class extends self.ISpriteInstance {},
	digordiebutton: class extends self.ISpriteInstance {},
	digordiebutton2: class extends self.ISpriteInstance {},
	coin2: class extends self.ITextInstance {},
	Usdt2: class extends self.ITextInstance {},
	coinpvp: class extends self.ISpriteInstance {},
	taskbar_4button: class extends self.ISpriteInstance {},
	task4_coin: class extends self.ISpriteInstance {},
	task4_text4: class extends self.ITextInstance {},
	AimSpotFamily: class extends self.ISpriteInstance {},
	AimSpotFamily2: class extends self.ISpriteInstance {}
}